### PR TITLE
Use LuaJITs pre-sized table allocated function if available

### PR DESCRIPTION
**Pull request by ccuser44**

### CODE REVIEW

**Comment by ccuser44** [comment]
Bump?

**Comment by ghost** [comment]
It might be cleaner to implement as a local function at this point, honestly. Something like...
```lua
local table_create

if table.create then
    table_create = table.create
elseif table.new then
    -- etc
end
```

Also might need alterations in the source templates.

**Comment by ccuser44** [comment]
> It might be cleaner to implement as a local function at this point, honestly. Something like...
> 
> ```lua
> local table_create
> 
> if table.create then
>     table_create = table.create
> elseif table.new then
>     -- etc
> end
> ```

Is it actually cleaner though. I feel like the alternate approach is more confusing especially when the other ones dont use the local method.

> Also might need alterations in the source templates.

This is also a downside to the localisation

**Comment by ghost** [comment]
I guess it's fine for now then.

**Pull request merged**
